spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gps
      host: localhost
      port: 27017
      database: gps
      username: wistoreuser
      password: wistoreuser@123456
      authentication-database: gps